### ISSUE TITLE
Exception from Tracker afterFlush function: dtp.setDate is not a function

### ISSUE THREAD

**Issue by rgnevashev** [aldeed/meteor-autoform-bs-datetimepicker#12]
I think in new 4 version setDate func doesnt exists. use date()

**Comment by boustanihani** [comment]
I'm getting this too after updatinf from 3 to 4 =>

```tsega:bootstrap3-datetimepicker*  upgraded from 3.1.3_3 to 4.0.0_4```

**Comment by aldeed** [comment]
I can do a release that supports 4 eventually, but for now you'll have to pin to 3.x.x.

**Comment by comerc** [comment]
You may use https://github.com/aldeed/meteor-autoform-bs-datetimepicker/issues/7 for support V4 now.

**Comment by tcastelli** [comment]
+1 :)

**Comment by flean** [comment]
Any updates on this and can you add the api.use 5.0.0? Thanks

**Comment by aldeed** [comment]
Now that AF5 is out, I'll be getting through issues and updating to datepicker 4 soon. I've released with api.use 5.

**Comment by eXon** [comment]
+1 this error is annoying

**Comment by flean** [comment]
Any updates on this?

**Comment by Asparagirl** [comment]
+1

**Comment by tylercreller** [comment]
+1, Still occurring

**Comment by BradRyan** [comment]
About a month ago I implemented the picker in my own form using tsega's package.  The timepicker docs are pretty good.  I'd recommend giving it a shot if you keep having issues with the autoform addon... I was in the same boat.

Package: https://atmospherejs.com/tsega/bootstrap3-datetimepicker

**Comment by Kostanos** [comment]
Fixed the setDate, but converted to String and added support for format: https://github.com/Kostanos/meteor-autoform-bs-datetimepicker

Need to test for return Date vs format before open pull request.

**Comment by aldeed** [comment]
Closing all issues. The plugin was a proof of concept which others have forked and made better alternatives.
